name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
    - run: npm --version
    - run: npm install
    - run: cat package.json
